replicaCount: 1

image:
  repository: ghcr.io/eumel8/prometheus-dashboard/prometheus-dashboard
  pullPolicy: Always
  #tag: 1.0.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

# minimal permissions for pod
podSecurityContext:
  fsGroup: 1000
  supplementalGroups:
  - 1000

# minimal permissions for container
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  runAsUser: 1000
  runAsGroup: 1000

# service for Webhook endpoint and Monitoring
service:
  type: ClusterIP
  monitorPort: 80
  targetPort: 8080

# resources for Container
resources:
  limits:
    memory: 250Mi
    cpu: 500m
  requests:
    memory: 64Mi
    cpu: 300m

nodeSelector: {}

tolerations: []

affinity: {}

# dashboard endpoint URLs
prometheusURL: "http://127.0.0.1:9090/api/v1/query"
alertmanagerURL: "http://127.0.0.1:9093/api/v2/alerts"

# use existing configMap with own index.html template
indexMap:
  enabled: false
  #name:  my-index-html
